# Generated by Django 3.0.3 on 2020-03-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CelticCross',
        ),
    ]
