# Generated by Django 3.0.3 on 2020-03-10 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelticCross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('pub_date', models.DateField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('crossing', models.ImageField(upload_to='images/')),
                ('foundation', models.ImageField(upload_to='images/')),
                ('behind', models.ImageField(upload_to='images/')),
                ('crowning', models.ImageField(upload_to='images/')),
                ('before', models.ImageField(upload_to='images/')),
                ('feelings', models.ImageField(upload_to='images/')),
                ('opinions', models.ImageField(upload_to='images/')),
                ('hopes', models.ImageField(upload_to='images/')),
                ('outcome', models.ImageField(upload_to='images/')),
                ('answer', models.TextField()),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
